# Generated by Django 5.2.4 on 2026-01-27 17:38

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_expense', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Record',
                'verbose_name_plural': 'Monthly Records',
                'db_table': 'monthly_records',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('source', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_records', to=settings.AUTH_USER_MODEL)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_entries', to='finance.monthly')),
            ],
            options={
                'verbose_name': 'Income Record',
                'verbose_name_plural': 'Income Records',
                'db_table': 'income_records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('store', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to=settings.AUTH_USER_MODEL)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to='finance.monthly')),
            ],
            options={
                'verbose_name': 'Daily Record',
                'verbose_name_plural': 'Daily Records',
                'db_table': 'daily_records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TravelDestinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Kraj')),
                ('city', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_destinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Travel Destination',
                'verbose_name_plural': 'Travel Destinations',
                'db_table': 'travel_destinations',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TravelExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('category', models.CharField(max_length=100)),
                ('travel_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finance.traveldestinations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Travel Expense',
                'verbose_name_plural': 'Travel Expenses',
                'db_table': 'travel_expenses',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='monthly',
            index=models.Index(fields=['user', 'date'], name='monthly_rec_user_id_89bb82_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthly',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_month'),
        ),
    ]
