# Generated by Django 5.2.4 on 2025-08-06 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_income', models.FloatField(default=0.0)),
                ('total_expense', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Record',
                'verbose_name_plural': 'Monthly Records',
                'db_table': 'monthly_records',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('source', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_records', to=settings.AUTH_USER_MODEL)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_entries', to='finance.monthly')),
            ],
            options={
                'verbose_name': 'Income Record',
                'verbose_name_plural': 'Income Records',
                'db_table': 'income_records',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('cost', models.FloatField()),
                ('store', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to=settings.AUTH_USER_MODEL)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to='finance.monthly')),
            ],
            options={
                'verbose_name': 'Daily Record',
                'verbose_name_plural': 'Daily Records',
                'db_table': 'daily_records',
                'ordering': ['-date'],
            },
        ),
    ]
