# Generated by Django 5.2.4 on 2025-12-20 15:44

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_daily_cost_alter_income_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelDestinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Kraj')),
                ('city', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_destinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Travel Destination',
                'verbose_name_plural': 'Travel Destinations',
                'db_table': 'travel_destinations',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TravelExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('category', models.CharField(max_length=100)),
                ('travel_destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finance.traveldestinations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Travel Expense',
                'verbose_name_plural': 'Travel Expenses',
                'db_table': 'travel_expenses',
                'ordering': ['-date'],
            },
        ),
    ]
