# Generated by Django 5.2.4 on 2026-05-04 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_finance_accounts_and_assign_records(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1])
    FinanceAccount = apps.get_model('finance', 'FinanceAccount')
    Monthly = apps.get_model('finance', 'Monthly')
    Daily = apps.get_model('finance', 'Daily')
    Income = apps.get_model('finance', 'Income')

    user_accounts = {}
    for user in User.objects.all():
        account = FinanceAccount.objects.create(
            owner_id=user.id,
            name='Konto osobiste',
            account_type='personal',
        )
        account.members.add(user)
        user_accounts[user.id] = account.id

    for monthly in Monthly.objects.all():
        monthly.account_id = user_accounts.get(monthly.user_id)
        monthly.save(update_fields=['account'])

    for daily in Daily.objects.all():
        daily.account_id = user_accounts.get(daily.user_id)
        daily.save(update_fields=['account'])

    for income in Income.objects.all():
        income.account_id = user_accounts.get(income.user_id)
        income.save(update_fields=['account'])


def reverse_create_finance_accounts_and_assign_records(apps, schema_editor):
    FinanceAccount = apps.get_model('finance', 'FinanceAccount')
    Monthly = apps.get_model('finance', 'Monthly')
    Daily = apps.get_model('finance', 'Daily')
    Income = apps.get_model('finance', 'Income')

    Monthly.objects.update(account=None)
    Daily.objects.update(account=None)
    Income.objects.update(account=None)
    FinanceAccount.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_traveldestinations_travelexpense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('personal', 'Konto osobiste'), ('shared', 'Konto wspólne')], default='personal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Finance Account',
                'verbose_name_plural': 'Finance Accounts',
                'db_table': 'finance_accounts',
                'ordering': ['account_type', 'name'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='monthly',
            name='unique_user_month',
        ),
        migrations.RemoveIndex(
            model_name='monthly',
            name='monthly_rec_user_id_89bb82_idx',
        ),
        migrations.AddField(
            model_name='income',
            name='linked_expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_shared_income', to='finance.daily'),
        ),
        migrations.AddField(
            model_name='financeaccount',
            name='members',
            field=models.ManyToManyField(related_name='finance_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financeaccount',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_finance_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='daily',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='finance.financeaccount'),
        ),
        migrations.AddField(
            model_name='daily',
            name='transfer_target_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfer_expenses', to='finance.financeaccount'),
        ),
        migrations.AddField(
            model_name='income',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_records', to='finance.financeaccount'),
        ),
        migrations.AddField(
            model_name='monthly',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_records', to='finance.financeaccount'),
        ),
        migrations.RunPython(
            create_finance_accounts_and_assign_records,
            reverse_create_finance_accounts_and_assign_records,
        ),
        migrations.AddIndex(
            model_name='monthly',
            index=models.Index(fields=['account', 'date'], name='monthly_rec_account_6b731c_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthly',
            constraint=models.UniqueConstraint(fields=('account', 'date'), name='unique_account_month'),
        ),
    ]
