# Generated by Django 5.2.4 on 2026-05-14 14:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_financeaccount_remove_monthly_unique_user_month_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerageAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('broker', models.CharField(choices=[('xtb', 'XTB'), ('mbank', 'mBank'), ('other', 'Inny broker')], max_length=20)),
                ('account_type', models.CharField(choices=[('standard', 'Zwykłe konto maklerskie'), ('ike', 'IKE')], default='standard', max_length=20)),
                ('currency', models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EUR'), ('USD', 'USD')], default='PLN', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brokerage_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'brokerage_accounts',
                'ordering': ['broker', 'account_type', 'currency', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BrokerageInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=160)),
                ('isin', models.CharField(blank=True, max_length=12)),
                ('exchange', models.CharField(blank=True, max_length=40)),
                ('asset_type', models.CharField(choices=[('stock', 'Akcja'), ('etf', 'ETF'), ('fund', 'Fundusz'), ('bond', 'Obligacja'), ('other', 'Inne')], default='stock', max_length=20)),
                ('currency', models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EUR'), ('USD', 'USD')], default='PLN', max_length=3)),
                ('last_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('last_price_at', models.DateTimeField(blank=True, null=True)),
                ('market_data_source', models.CharField(blank=True, max_length=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brokerage_instruments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'brokerage_instruments',
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='BrokerageDividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_dividend_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField()),
                ('gross_amount_per_share', models.DecimalField(decimal_places=6, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('currency', models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EUR'), ('USD', 'USD')], max_length=3)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('19.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('planned', 'Planowana'), ('paid', 'Wypłacona')], default='planned', max_length=20)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='finance.brokerageaccount')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='finance.brokerageinstrument')),
            ],
            options={
                'db_table': 'brokerage_dividends',
                'ordering': ['payment_date', 'instrument__ticker'],
            },
        ),
        migrations.CreateModel(
            name='BrokerageTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'Kupno'), ('sell', 'Sprzedaż')], max_length=10)),
                ('trade_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('price', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fx_rate_to_pln', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Kurs waluty transakcji do PLN używany do szacowania podatku i wartości portfela.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.brokerageaccount')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.brokerageinstrument')),
            ],
            options={
                'db_table': 'brokerage_transactions',
                'ordering': ['-trade_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='brokerageaccount',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_brokerage_account_name'),
        ),
        migrations.AddConstraint(
            model_name='brokerageinstrument',
            constraint=models.UniqueConstraint(fields=('user', 'ticker'), name='unique_user_brokerage_ticker'),
        ),
        migrations.AddIndex(
            model_name='brokeragedividend',
            index=models.Index(fields=['account', 'payment_date'], name='brokerage_d_account_12743e_idx'),
        ),
        migrations.AddIndex(
            model_name='brokeragetransaction',
            index=models.Index(fields=['account', 'instrument', 'trade_date'], name='brokerage_t_account_e7767a_idx'),
        ),
    ]
