# Generated by Django 5.2.4 on 2026-05-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_brokerageaccount_brokerageinstrument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokeragetransaction',
            name='market_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='brokeragetransaction',
            name='market_price_source',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='brokeragetransaction',
            name='trade_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
