# Generated by Django 5.2.4 on 2026-05-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_brokeragetransaction_market_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerageinstrument',
            name='price_symbol',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
