# Generated by Django 5.2.4 on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_brokerageinstrument_price_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldestinations',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='traveldestinations',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
