# Generated by Django 5.2.4 on 2026-05-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_traveldestinations_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldestinations',
            name='travel_type',
            field=models.CharField(
                choices=[('leisure', 'Wakacje'), ('business', 'Delegacja')],
                default='leisure',
                max_length=20,
            ),
        ),
    ]
