# Generated by Codex on 2026-05-17

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_traveldestinations_travel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokeragetransaction',
            name='external_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='brokeragetransaction',
            name='import_source',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddConstraint(
            model_name='brokeragetransaction',
            constraint=models.UniqueConstraint(
                condition=~Q(external_id=''),
                fields=('account', 'external_id'),
                name='unique_brokerage_account_external_transaction',
            ),
        ),
    ]
