# Generated by Codex on 2026-07-30

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_brokeragetransaction_import_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily',
            name='external_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='daily',
            name='import_source',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='income',
            name='external_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='income',
            name='import_source',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddConstraint(
            model_name='daily',
            constraint=models.UniqueConstraint(
                condition=~Q(external_id=''),
                fields=('account', 'external_id'),
                name='unique_daily_account_external_transaction',
            ),
        ),
        migrations.AddConstraint(
            model_name='income',
            constraint=models.UniqueConstraint(
                condition=~Q(external_id=''),
                fields=('account', 'external_id'),
                name='unique_income_account_external_transaction',
            ),
        ),
    ]
