# Generated by Codex on 2026-08-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_daily_income_import_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='counterparty',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
