# Generated by Django 5.2.4 on 2026-08-10 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_income_counterparty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerageCashOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('deposit', 'Wpłata'), ('withdrawal', 'Wypłata'), ('internal_transfer', 'Przelew wewnętrzny'), ('buy', 'Kupno'), ('sell', 'Sprzedaż'), ('dividend', 'Dywidenda'), ('withholding_tax', 'Podatek u źródła'), ('interest', 'Odsetki'), ('interest_tax', 'Podatek od odsetek'), ('fee', 'Opłata'), ('other', 'Inna operacja')], max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency', models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EUR'), ('USD', 'USD')], max_length=3)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('position_external_id', models.CharField(blank=True, max_length=120)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('product', models.CharField(blank=True, max_length=255)),
                ('import_source', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'brokerage_cash_operations',
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BrokeragePositionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateTimeField()),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('market_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('current_price', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('profit_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('currency', models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EUR'), ('USD', 'USD')], max_length=3)),
                ('source', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'db_table': 'brokerage_position_snapshots',
                'ordering': ['-as_of', 'instrument__ticker'],
            },
        ),
        migrations.CreateModel(
            name='BrokeragePriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('source', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'db_table': 'brokerage_price_snapshots',
                'ordering': ['-observed_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('matched', 'Dopasowane'), ('needs_review', 'Wymaga weryfikacji')], default='pending', max_length=20)),
                ('source_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('source_currency', models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EUR'), ('USD', 'USD')], default='PLN', max_length=3)),
                ('occurred_on', models.DateField()),
                ('match_method', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'investment_fundings',
                'ordering': ['-occurred_on', '-id'],
            },
        ),
        migrations.AddField(
            model_name='brokerageaccount',
            name='external_account_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='brokerageaccount',
            name='last_import_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='daily',
            name='brokerage_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_expenses', to='finance.brokerageaccount'),
        ),
        migrations.AddConstraint(
            model_name='brokerageaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('external_account_id', ''), _negated=True), fields=('user', 'broker', 'external_account_id'), name='unique_user_broker_external_account'),
        ),
        migrations.AddField(
            model_name='brokeragecashoperation',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_operations', to='finance.brokerageaccount'),
        ),
        migrations.AddField(
            model_name='brokeragecashoperation',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_operations', to='finance.brokerageinstrument'),
        ),
        migrations.AddField(
            model_name='brokeragepositionsnapshot',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_snapshots', to='finance.brokerageaccount'),
        ),
        migrations.AddField(
            model_name='brokeragepositionsnapshot',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_snapshots', to='finance.brokerageinstrument'),
        ),
        migrations.AddField(
            model_name='brokeragepricesnapshot',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_snapshots', to='finance.brokerageinstrument'),
        ),
        migrations.AddField(
            model_name='investmentfunding',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_fundings', to='finance.brokerageaccount'),
        ),
        migrations.AddField(
            model_name='investmentfunding',
            name='cash_operation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_funding', to='finance.brokeragecashoperation'),
        ),
        migrations.AddField(
            model_name='investmentfunding',
            name='expense',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investment_funding', to='finance.daily'),
        ),
        migrations.AddIndex(
            model_name='brokeragecashoperation',
            index=models.Index(fields=['account', 'occurred_at'], name='brokerage_c_account_11c049_idx'),
        ),
        migrations.AddIndex(
            model_name='brokeragecashoperation',
            index=models.Index(fields=['instrument', 'occurred_at'], name='brokerage_c_instrum_fea8a3_idx'),
        ),
        migrations.AddIndex(
            model_name='brokeragecashoperation',
            index=models.Index(fields=['account', 'operation_type', 'occurred_at'], name='brokerage_c_account_471ca2_idx'),
        ),
        migrations.AddConstraint(
            model_name='brokeragecashoperation',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('account', 'import_source', 'external_id'), name='unique_broker_cash_import_operation'),
        ),
        migrations.AddIndex(
            model_name='brokeragepositionsnapshot',
            index=models.Index(fields=['account', 'as_of'], name='brokerage_p_account_f3cd88_idx'),
        ),
        migrations.AddIndex(
            model_name='brokeragepositionsnapshot',
            index=models.Index(fields=['instrument', 'as_of'], name='brokerage_p_instrum_b33c45_idx'),
        ),
        migrations.AddConstraint(
            model_name='brokeragepositionsnapshot',
            constraint=models.UniqueConstraint(fields=('account', 'instrument', 'as_of'), name='unique_broker_position_snapshot'),
        ),
        migrations.AddIndex(
            model_name='brokeragepricesnapshot',
            index=models.Index(fields=['instrument', 'observed_at'], name='brokerage_p_instrum_a74a95_idx'),
        ),
        migrations.AddConstraint(
            model_name='brokeragepricesnapshot',
            constraint=models.UniqueConstraint(fields=('instrument', 'observed_at'), name='unique_broker_price_snapshot'),
        ),
        migrations.AddIndex(
            model_name='investmentfunding',
            index=models.Index(fields=['account', 'occurred_on'], name='investment__account_f70e1a_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentfunding',
            index=models.Index(fields=['status', 'occurred_on'], name='investment__status_6ac133_idx'),
        ),
    ]
