# Generated by Django 5.2.4 on 2026-08-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_brokeragecashoperation_brokeragepositionsnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerageinstrument',
            name='history_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brokerageinstrument',
            name='history_sync_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='brokerageinstrument',
            name='history_synced_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brokerageinstrument',
            name='history_synced_through',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BrokerageDailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_date', models.DateField()),
                ('open', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('close', models.DecimalField(decimal_places=6, max_digits=18)),
                ('adjusted_close', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('provider_symbol', models.CharField(blank=True, max_length=32)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('is_final', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_prices', to='finance.brokerageinstrument')),
            ],
            options={
                'db_table': 'brokerage_daily_prices',
                'ordering': ['trading_date'],
                'indexes': [models.Index(fields=['instrument', 'trading_date'], name='broker_dly_instr_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('instrument', 'trading_date'), name='unique_broker_daily_price')],
            },
        ),
    ]
