# Generated by Django 5.2.4 on 2026-10-09 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0015_brokeragedailyprice_and_history_sync"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("expense", "Wydatek"), ("income", "Przychód")],
                        default="expense",
                        max_length=10,
                    ),
                ),
                ("patterns", models.TextField()),
                ("label", models.CharField(max_length=100)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("store_name", models.CharField(blank=True, max_length=255)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_rules",
                        to="finance.financeaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_import_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Import Rule",
                "verbose_name_plural": "Import Rules",
                "db_table": "finance_import_rules",
                "ordering": ["account", "kind", "position", "id"],
            },
        ),
    ]
