# Generated by Django 5.2.4 on 2026-05-20 17:08

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0002_alter_recipe_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PantryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('unit', models.CharField(choices=[('szt', 'szt.'), ('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('opak', 'opak.')], default='szt', max_length=10)),
                ('current_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('minimum_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('restock_lead_days', models.PositiveSmallIntegerField(default=3)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pantry_products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PantryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('purchase', 'Uzupełnienie'), ('consume', 'Zużycie'), ('adjust', 'Korekta')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('occurred_on', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='cooking.pantryproduct')),
            ],
            options={
                'db_table': 'pantry_movements',
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='pantryproduct',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_pantry_product_name'),
        ),
    ]
