# Generated by Django 5.2.4 on 2026-05-20 18:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0003_pantryproduct_pantrymovement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('instruction', models.TextField()),
                ('mix_after', models.BooleanField(default=False)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='cooking.recipe')),
            ],
            options={
                'db_table': 'recipe_steps',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RecipeStepIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=160)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('unit', models.CharField(choices=[('szt', 'szt.'), ('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('opak', 'opak.')], default='g', max_length=10)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cooking.recipestep')),
            ],
            options={
                'db_table': 'recipe_step_ingredients',
                'ordering': ['step__order', 'order', 'id'],
            },
        ),
    ]
