# Generated by Django 5.2.4 on 2026-05-28 19:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooking', '0004_recipestep_recipestepingredient'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('source', models.CharField(choices=[('manual', 'Ręczna'), ('automatic', 'Automatyczna')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Aktywna'), ('completed', 'Zakończona')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shopping_lists',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit', models.CharField(choices=[('szt', 'szt.'), ('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('opak', 'opak.')], default='szt', max_length=10)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('is_purchased', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pantry_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopping_items', to='cooking.pantryproduct')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cooking.shoppinglist')),
            ],
            options={
                'db_table': 'shopping_list_items',
                'ordering': ['is_purchased', 'category', 'name'],
            },
        ),
    ]
