# Generated by Django 5.2.4 on 2026-09-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooking", "0009_pantrymovement_fulfilled_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcatalogentry",
            name="name_language",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name="productcatalogentry",
            name="source",
            field=models.CharField(
                choices=[
                    ("open_food_facts", "Open Food Facts"),
                    ("household", "Zapamiętane w domu"),
                ],
                default="open_food_facts",
                max_length=40,
            ),
        ),
    ]
