# Generated by Django 5.2.4 on 2026-09-21 07:35

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooking", "0016_push_notifications"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("category", models.CharField(blank=True, max_length=120)),
                ("minimum_packages", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utworzona przez",
                    ),
                ),
            ],
            options={
                "db_table": "product_groups",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="pantryproduct",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="cooking.productgroup",
                verbose_name="Grupa produktów",
            ),
        ),
        migrations.AddField(
            model_name="shoppinglistitem",
            name="pantry_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shopping_items",
                to="cooking.productgroup",
            ),
        ),
        migrations.AddConstraint(
            model_name="productgroup",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="unique_product_group_name_ci",
            ),
        ),
    ]
