# Generated by Django 5.2.4 on 2026-09-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooking", "0017_product_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="pantryproduct",
            name="one_off",
            field=models.BooleanField(
                default=False,
                help_text="Bez prognozy zakupu i bez listy zakupów; stan i historia zostają.",
                verbose_name="Nie kupuję ponownie",
            ),
        ),
    ]
