# Generated by Django 5.2.4 on 2026-10-03 16:15

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cooking", "0020_shopping_list_uuid_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="PantryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "group",
                    models.CharField(
                        choices=[("food", "Spożywcze"), ("home", "Dom")],
                        default="food",
                        max_length=10,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "code",
                    models.SlugField(blank=True, max_length=40, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "pantry_categories",
                "ordering": ["group", "position", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="unique_pantry_category_name_ci",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PantryCategoryRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("keywords", "Słowa kluczowe"),
                            ("tags", "Tagi Open Food Facts"),
                        ],
                        default="keywords",
                        max_length=10,
                    ),
                ),
                ("patterns", models.TextField()),
                ("position", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="cooking.pantrycategory",
                    ),
                ),
            ],
            options={
                "db_table": "pantry_category_rules",
                "ordering": ["kind", "position", "id"],
            },
        ),
    ]
