"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import sys
from pathlib import Path
from urllib.parse import unquote, urlparse
from django.core.exceptions import ImproperlyConfigured
from django.contrib.messages import constants as messages
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_list(name, default=''):
    return [item.strip() for item in os.environ.get(name, default).split(',') if item.strip()]


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value in ['1', 'True', 'true', 'yes', 'on']


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', False)
RUNNING_TESTS = 'test' in sys.argv
CI = env_bool('CI', False) or env_bool('GITHUB_ACTIONS', False)
NON_PRODUCTION_CONTEXT = DEBUG or RUNNING_TESTS or CI

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if NON_PRODUCTION_CONTEXT:
        SECRET_KEY = 'django-insecure-local-development-only-change-me'
    else:
        raise ImproperlyConfigured('Set SECRET_KEY before running with DEBUG disabled.')

ALLOWED_HOSTS = env_list(
    'ALLOWED_HOSTS',
    'localhost,127.0.0.1,[::1]' if NON_PRODUCTION_CONTEXT else '',
)
if not NON_PRODUCTION_CONTEXT and (not ALLOWED_HOSTS or '*' in ALLOWED_HOSTS):
    raise ImproperlyConfigured('Set explicit ALLOWED_HOSTS before running with DEBUG disabled.')

CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS')
if not CSRF_TRUSTED_ORIGINS:
    csrf_ports = env_list('CSRF_TRUSTED_PORTS', '8000')
    for host in ALLOWED_HOSTS:
        if host == '*':
            continue
        hosts = [host]
        if ':' not in host:
            hosts.extend(f'{host}:{port}' for port in csrf_ports)
        for trusted_host in hosts:
            CSRF_TRUSTED_ORIGINS.extend([f'http://{trusted_host}', f'https://{trusted_host}'])

CSRF_COOKIE_SAMESITE = os.environ.get('CSRF_COOKIE_SAMESITE', 'Lax')
SESSION_COOKIE_SAMESITE = os.environ.get('SESSION_COOKIE_SAMESITE', 'Lax')
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', False)
SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', False)
CSRF_FAILURE_VIEW = 'config.views.csrf_failure'
SESSION_COOKIE_HTTPONLY = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = os.environ.get('SECURE_REFERRER_POLICY', 'same-origin')
SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', False)
# Za Caddy (usługa "caddy" w docker-compose) Django dostaje zwykłe HTTP
# z nagłówkiem X-Forwarded-Proto. Bez tego request.is_secure() zwraca False
# dla strony otwartej przez HTTPS, a sprawdzanie Origin w CSRF porównuje
# "https://host" z "http://host" i odrzuca każdy formularz. Włączane tylko
# zmienną, bo nagłówek wolno ufać wyłącznie wtedy, gdy stawia go proxy.
if env_bool('BEHIND_HTTPS_PROXY', False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', False)
SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', False)
ALLOW_PUBLIC_SIGNUP = env_bool('ALLOW_PUBLIC_SIGNUP', DEBUG)

# Podgląd importu bankowego wysyła około 10 pól na każdy wiersz transakcji.
# Domyślny limit Django (1000) blokował import już przy około 100 pozycjach.
DATA_UPLOAD_MAX_NUMBER_FIELDS = int(os.environ.get('DATA_UPLOAD_MAX_NUMBER_FIELDS', '20000'))


# Application definition

INSTALLED_APPS = [
    'cars',
    'finance',
    'habits',
    'rest_framework',
    'accounts',
    'cooking',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_countries',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # global templates/
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.account_access',
                'finance.context_processors.finance_accounts',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

database_url = os.environ.get('DATABASE_URL')
if database_url:
    parsed_database_url = urlparse(database_url)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': parsed_database_url.path.lstrip('/'),
            'USER': unquote(parsed_database_url.username or ''),
            'PASSWORD': unquote(parsed_database_url.password or ''),
            'HOST': parsed_database_url.hostname or 'localhost',
            'PORT': str(parsed_database_url.port or ''),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': (
                os.environ.get('DATABASE_NAME')
                or os.environ.get('DB_NAME')
                or os.environ.get('POSTGRES_DB', 'finance_db')
            ),
            'USER': (
                os.environ.get('DATABASE_USER')
                or os.environ.get('DB_USER')
                or os.environ.get('POSTGRES_USER', 'finance_user')
            ),
            'PASSWORD': (
                os.environ.get('DATABASE_PASSWORD')
                or os.environ.get('DB_PASSWORD')
                or os.environ.get('POSTGRES_PASSWORD', 'finance_pass')
            ),
            'HOST': (
                os.environ.get('DATABASE_HOST')
                or os.environ.get('DB_HOST')
                or os.environ.get('POSTGRES_HOST', 'localhost')
            ),
            'PORT': (
                os.environ.get('DATABASE_PORT')
                or os.environ.get('DB_PORT')
                or os.environ.get('POSTGRES_PORT', '5432')
            ),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
}

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pl'

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_TZ = True
USE_L10N = True
USE_THOUSAND_SEPARATOR = True

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
PRIVATE_MEDIA_ROOT = BASE_DIR / 'private_media'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Zasoby wspólne dla całego projektu, niezwiązane z jedną aplikacją:
# static/vendor/ trzyma biblioteki frontendowe (Bootstrap, Chart.js, Leaflet,
# flatpickr, summernote), które wcześniej ładowały się z CDN-ów. Serwer domowy
# w LAN-ie ma działać bez internetu, a lokalne pliki ładują się szybciej
# i nie ujawniają ruchu użytkowników zewnętrznym dostawcom.
STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_STORAGE_BACKEND = (
    'django.contrib.staticfiles.storage.StaticFilesStorage'
    if RUNNING_TESTS
    else 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
)
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': STATICFILES_STORAGE_BACKEND,
    },
}
# Jak długo przeglądarka może trzymać plik statyczny bez pytania serwera.
#
# Z DEBUG=False ManifestStaticFilesStorage wkleja skrót treści w nazwę pliku
# (ui.a1b2c3.css), więc zmiana arkusza zmienia adres i tydzień w cache jest
# bezpieczny - stary adres po prostu przestaje być używany.
#
# Z DEBUG=True Django celowo zwraca adresy BEZ skrótu (HashedFilesMixin._url
# omija hashowanie, gdy settings.DEBUG). Adres zostaje ten sam po każdej
# edycji CSS, więc tydzień w cache oznacza, że przeglądarka przez tydzień
# podaje starą wersję arkusza i poprawki "nie działają" - zwykłe odświeżenie
# nawet nie pyta serwera, bo wpis w cache jest jeszcze świeży. W trybie
# deweloperskim plik musi więc być zawsze walidowany.
WHITENOISE_MAX_AGE = 0 if DEBUG else 60 * 60 * 24 * 7

# Cache
# Domyślny LocMemCache jest cache'em per-proces, a gunicorn uruchamia kilka
# workerów - ten sam wykres historii portfela liczyłby się osobno w każdym
# z nich. Cache plikowy leży we wspólnym systemie plików kontenera, więc
# workery współdzielą wpisy bez dodatkowej usługi (Redis/Memcached).
# Testy zostają na LocMemCache, żeby nie dotykać dysku i nie wyciekać stanu
# między przypadkami testowymi.
if RUNNING_TESTS:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'website-finance-tests',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': os.environ.get(
                'CACHE_BACKEND',
                'django.core.cache.backends.filebased.FileBasedCache',
            ),
            'LOCATION': os.environ.get('CACHE_LOCATION', '/tmp/website-finance-cache'),
            'TIMEOUT': int(os.environ.get('CACHE_TIMEOUT', '300')),
            'OPTIONS': {
                'MAX_ENTRIES': int(os.environ.get('CACHE_MAX_ENTRIES', '1000')),
            },
        }
    }

ALPHA_VANTAGE_API_KEY = os.environ.get('ALPHA_VANTAGE_API_KEY', '')
OPENFIGI_API_KEY = os.environ.get('OPENFIGI_API_KEY', '')
STOOQ_API_KEY = os.environ.get('STOOQ_API_KEY', '')
TRAVEL_GEOCODING_ENABLED = env_bool('TRAVEL_GEOCODING_ENABLED', True)
TRAVEL_GEOCODING_TIMEOUT = float(os.environ.get('TRAVEL_GEOCODING_TIMEOUT', '3'))
TRAVEL_GEOCODING_USER_AGENT = os.environ.get(
    'TRAVEL_GEOCODING_USER_AGENT',
    'Website-Finance travel map geocoder',
)
OPEN_FOOD_FACTS_ENABLED = env_bool('OPEN_FOOD_FACTS_ENABLED', True)
OPEN_FOOD_FACTS_TIMEOUT = float(os.environ.get('OPEN_FOOD_FACTS_TIMEOUT', '2.5'))
OPEN_FOOD_FACTS_RATE_LIMIT = int(os.environ.get('OPEN_FOOD_FACTS_RATE_LIMIT', '12'))
OPEN_FOOD_FACTS_IMAGE_MAX_BYTES = int(
    os.environ.get('OPEN_FOOD_FACTS_IMAGE_MAX_BYTES', str(2 * 1024 * 1024))
)
OPEN_FOOD_FACTS_USER_AGENT = (
    os.environ.get('OPEN_FOOD_FACTS_USER_AGENT')
    or 'WebsiteFinance/1.0 (https://github.com/famousDeer/Personal_Website)'
).strip()

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MESSAGE_TAGS = {
    messages.DEBUG: 'debug',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = 'login'

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2 weeks in sec
