# Generated by Django 5.2.4 on 2025-12-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carfuelconsumption',
            old_name='fuel_staton',
            new_name='fuel_station',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='yaer',
            new_name='year',
        ),
        migrations.AlterField(
            model_name='cars',
            name='fuel_type',
            field=models.CharField(choices=[('Benzyna', 'Benzyna'), ('Diesel', 'Diesel'), ('Elektryczny', 'Elektryczny'), ('Hybryda', 'Hybryda'), ('LPG', 'LPG')], default='Benzyna', max_length=50),
        ),
    ]
