# Generated by Django 5.2.4 on 2026-01-23 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_fuel_staton_carfuelconsumption_fuel_station_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartyres',
            name='size',
        ),
        migrations.AddField(
            model_name='carfuelconsumption',
            name='price_per_liter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='cartyres',
            name='aspect_ratio',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cartyres',
            name='diameter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cartyres',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='cartyres',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
