# Generated by Django 5.2.4 on 2026-04-08 08:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_cartyres_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carservice',
            name='workshop_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='carservice',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='CarServicePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='cars.carservice')),
            ],
            options={
                'verbose_name': 'Car Service Part',
                'verbose_name_plural': 'Car Service Parts',
                'db_table': 'car_service_parts',
                'ordering': ['id'],
            },
        ),
    ]
