# Generated by Django 5.2.4 on 2026-10-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0006_make_tyre_purchase_odometer_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="carservice",
            name="odometer",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
